import React from 'react';
import { ComponentType, CanvasComponent, Preset } from './types';
import { MailIcon, BellIcon, HomeIcon, UserIcon, CogIcon, SearchIcon, CheckCircleIcon, XCircleIcon, InformationCircleIcon, ExclamationTriangleIcon, SparklesIcon, LoaderIcon, TabsIcon, DropdownIcon, RadioGroupIcon, ToggleIcon, SliderIcon, ProgressIcon, ModalIcon, PopoverIcon, TextIcon, ImageIcon, ContainerIcon, AccordionIcon, BarChartIcon, LineChartIcon, PieChartIcon, PlayIcon, PauseIcon, ForwardIcon, BackwardIcon, QuestionMarkCircleIcon, XMarkIcon, ListboxIcon } from './components/icons';

export const TOOLBOX_COMPONENTS = [
  { type: ComponentType.Container, name: '컨테이너', icon: ContainerIcon },
  { type: ComponentType.Text, name: '텍스트', icon: TextIcon },
  { type: ComponentType.Button, name: '버튼', icon: SparklesIcon },
  { type: ComponentType.Input, name: '입력 필드', icon: SearchIcon },
  { type: ComponentType.Listbox, name: '목록상자', icon: ListboxIcon },
  { type: ComponentType.Image, name: '이미지', icon: ImageIcon },
  { type: ComponentType.Tabs, name: '탭', icon: TabsIcon },
  { type: ComponentType.Accordion, name: '아코디언', icon: AccordionIcon },
  { type: ComponentType.Dropdown, name: '드롭다운', icon: DropdownIcon },
  { type: ComponentType.Radio, name: '라디오', icon: RadioGroupIcon },
  { type: ComponentType.Checkbox, name: '체크박스', icon: CheckCircleIcon },
  { type: ComponentType.Toggle, name: '토글', icon: ToggleIcon },
  { type: ComponentType.Slider, name: '슬라이더', icon: SliderIcon },
  { type: ComponentType.Alert, name: '알림', icon: ExclamationTriangleIcon },
  { type: ComponentType.Loader, name: '로더', icon: LoaderIcon },
  { type: ComponentType.Progress, name: '진행률', icon: ProgressIcon },
  { type: ComponentType.Tooltip, name: '툴팁', icon: InformationCircleIcon },
  { type: ComponentType.Modal, name: '모달', icon: ModalIcon },
  { type: ComponentType.Popover, name: '팝오버', icon: PopoverIcon },
  { type: ComponentType.Icon, name: '아이콘', icon: UserIcon },
  { type: ComponentType.BarChart, name: '막대 차트', icon: BarChartIcon },
  { type: ComponentType.LineChart, name: '선 차트', icon: LineChartIcon },
  { type: ComponentType.PieChart, name: '파이 차트', icon: PieChartIcon },
  { type: ComponentType.Misc, name: '기타', icon: QuestionMarkCircleIcon },
];

export const TOOLTIP_DESCRIPTIONS: Record<string, string> = {
  [ComponentType.Container]: '다른 요소들을 그룹화하거나 레이아웃을 구성하는 데 사용되는 기본 컨테이너입니다.',
  [ComponentType.Text]: '자유롭게 텍스트를 입력하고 스타일을 지정할 수 있습니다. 더블 클릭하여 내용을 수정하세요.',
  [ComponentType.Button]: '사용자의 클릭과 같은 상호작용을 유도하는 버튼입니다. 다양한 스타일을 적용할 수 있습니다.',
  [ComponentType.Input]: '사용자로부터 텍스트 입력을 받기 위한 필드입니다. Placeholder 텍스트를 설정할 수 있습니다.',
  [ComponentType.Listbox]: '여러 항목을 목록 형태로 보여주고, 사용자가 하나를 선택할 수 있도록 하는 컴포넌트입니다.',
  [ComponentType.Image]: 'URL을 통해 이미지를 캔버스에 추가합니다. 다양한 object-fit 스타일을 적용할 수 있습니다.',
  [ComponentType.Tabs]: '여러 컨텐츠 섹션을 전환하며 보여줄 수 있는 탭 인터페이스입니다. 탭 추가/삭제가 가능합니다.',
  [ComponentType.Accordion]: '여러 섹션을 접고 펼 수 있는 아코디언 인터페이스입니다. 각 항목의 제목과 내용을 수정할 수 있습니다.',
  [ComponentType.Dropdown]: '여러 옵션 중 하나를 선택할 수 있는 드롭다운 메뉴입니다.',
  [ComponentType.Radio]: '여러 선택지 중 단 하나만 선택할 수 있는 라디오 버튼입니다.',
  [ComponentType.Checkbox]: '하나 또는 여러 개의 옵션을 선택/해제할 수 있는 체크박스입니다.',
  [ComponentType.Toggle]: 'On/Off와 같은 두 가지 상태를 전환하는 스위치입니다.',
  [ComponentType.Slider]: '일정 범위 내의 값을 조절할 수 있는 슬라이더입니다.',
  [ComponentType.Alert]: '사용자에게 정보, 성공, 경고, 오류 등의 메시지를 전달하는 알림 컴포넌트입니다.',
  [ComponentType.Loader]: '데이터를 불러오는 중임을 시각적으로 나타내는 로딩 스피너입니다.',
  [ComponentType.Progress]: '작업의 진행 상태를 시각적으로 보여주는 진행률 막대입니다.',
  [ComponentType.Tooltip]: '특정 요소에 마우스를 올렸을 때 추가 정보를 제공하는 말풍선입니다.',
  [ComponentType.Modal]: '기존 화면 위에 오버레이되어 중요한 정보나 작업을 표시하는 모달 창입니다.',
  [ComponentType.Popover]: '특정 요소를 클릭했을 때 나타나는 작은 정보 창입니다.',
  [ComponentType.Icon]: '다양한 벡터 아이콘을 캔버스에 추가하여 시각적 의미를 전달합니다.',
  [ComponentType.BarChart]: '데이터를 막대 형태로 시각화하는 차트입니다. JSON 형식으로 데이터를 수정할 수 있습니다.',
  [ComponentType.LineChart]: '시간의 흐름이나 추세에 따른 데이터 변화를 선으로 나타내는 차트입니다.',
  [ComponentType.PieChart]: '전체에 대한 각 부분의 비율을 원형으로 나타내는 차트입니다.',
  [ComponentType.Group]: '여러 컴포넌트를 하나로 묶어 관리하는 컨테이너입니다. 그룹을 선택하고 이동, 복제, 삭제할 수 있습니다.',
  [ComponentType.Misc]: '설명을 입력하여 사용자 정의 컴포넌트를 만듭니다. 이 컴포넌트는 입력된 설명을 표시합니다.',
};

const commonStyles = {
  backgroundColor: '#374151',
  borderColor: '#6b7280',
  borderWidth: 1,
  borderRadius: 6,
  color: '#ffffff',
};

export const DEFAULT_PROPS: Omit<CanvasComponent, 'id' | 'position'>[] = [
  { name: '', type: ComponentType.Button, props: { text: '버튼', kind: 'text', icon: null }, size: { width: 88, height: 40 }, styles: { ...commonStyles, backgroundColor: '#2563eb', borderWidth: 0, fontSize: 14, fontWeight: 600 }, description: '', isLocked: false },
  { name: '', type: ComponentType.Input, props: { placeholder: '텍스트 입력...' }, size: { width: 200, height: 40 }, styles: { ...commonStyles, paddingLeft: 12 }, description: '', isLocked: false },
  { name: '', type: ComponentType.Listbox, props: { items: ['항목 1', '항목 2', '항목 3'], selectedIndex: 0 }, size: { width: 200, height: 120 }, styles: { ...commonStyles }, description: '', isLocked: false },
  { name: '', type: ComponentType.Text, props: { text: '텍스트를 입력하세요' }, size: { width: 180, height: 36 }, styles: { fontSize: 16, fontWeight: 400, color: '#ffffff', textAlign: 'left', backgroundColor: 'transparent', padding: '4px 8px' }, description: '', isLocked: false },
  { name: '', type: ComponentType.Tabs, props: { tabs: ['탭 1', '탭 2'], activeTab: 0, style: 'line' }, size: { width: 240, height: 40 }, styles: {}, description: '', isLocked: false },
  { name: '', type: ComponentType.Accordion, props: { items: [{ title: '항목 1', content: '첫 번째 항목의 내용입니다.' }, { title: '항목 2', content: '두 번째 항목의 내용입니다.' }], openItem: 0 }, size: { width: 300, height: 150 }, styles: { ...commonStyles, backgroundColor: '#1f2937', borderColor: '#374151' }, description: '', isLocked: false },
  { name: '', type: ComponentType.Dropdown, props: { options: ['옵션 1', '옵션 2', '옵션 3'], isOpen: false }, size: { width: 200, height: 40 }, styles: { ...commonStyles }, description: '', isLocked: false },
  { name: '', type: ComponentType.Radio, props: { name: 'radio-group', checked: false, label: '라디오 버튼' }, size: { width: 120, height: 24 }, styles: { color: '#ffffff', fontSize: 14 }, description: '', isLocked: false },
  { name: '', type: ComponentType.Checkbox, props: { checked: false, label: '체크박스' }, size: { width: 120, height: 24 }, styles: { color: '#ffffff', fontSize: 14 }, description: '', isLocked: false },
  { name: '', type: ComponentType.Toggle, props: { isOn: false, leftLabel: '', rightLabel: '' }, size: { width: 120, height: 28 }, styles: {}, description: '', isLocked: false },
  { name: '', type: ComponentType.Slider, props: { value: 50 }, size: { width: 200, height: 24 }, styles: {}, description: '', isLocked: false },
  { name: '', type: ComponentType.Alert, props: { text: '알림 메시지입니다.', type: 'info', dismissible: false }, size: { width: 320, height: 60 }, styles: {}, description: '', isLocked: false },
  { name: '', type: ComponentType.Loader, props: { style: 'spinner' }, size: { width: 32, height: 32 }, styles: {}, description: '', isLocked: false },
  { name: '', type: ComponentType.Progress, props: { progress: 60, showLabel: false }, size: { width: 200, height: 10 }, styles: { backgroundColor: '#4b5563', barColor: '#2563eb' }, description: '', isLocked: false },
  { name: '', type: ComponentType.Tooltip, props: { text: '툴팁 텍스트' }, size: { width: 32, height: 32 }, styles: {}, description: '', isLocked: false },
  { name: '', type: ComponentType.Modal, props: { title: '모달 제목', content: '모달 내용입니다.' }, size: { width: 384, height: 220 }, styles: { ...commonStyles, backgroundColor: '#1f2937' }, description: '', isLocked: false },
  { name: '', type: ComponentType.Popover, props: { title: '팝오버 제목', placement: 'bottom' }, size: { width: 256, height: 120 }, styles: { ...commonStyles }, description: '', isLocked: false },
  { name: '', type: ComponentType.Icon, props: { icon: 'HomeIcon' }, size: { width: 24, height: 24 }, styles: { color: '#9ca3af' }, description: '', isLocked: false },
  { name: '', type: ComponentType.Image, props: { src: 'https://picsum.photos/200/300' }, size: { width: 200, height: 150 }, styles: { objectFit: 'cover', borderRadius: 8 }, description: '', isLocked: false },
  { name: '', type: ComponentType.Container, props: {}, size: { width: 250, height: 180 }, styles: { ...commonStyles, backgroundColor: 'rgba(55, 65, 81, 0.5)', borderWidth: 1, borderColor: '#4b5563' }, description: '', isLocked: false },
  { name: '', type: ComponentType.BarChart, props: { colors: ['#8884d8', '#82ca9d'] }, size: { width: 400, height: 250 }, styles: { ...commonStyles, backgroundColor: 'rgba(55, 65, 81, 0.5)' }, description: '', isLocked: false },
  { name: '', type: ComponentType.LineChart, props: { colors: ['#8884d8', '#82ca9d'] }, size: { width: 400, height: 250 }, styles: { ...commonStyles, backgroundColor: 'rgba(55, 65, 81, 0.5)' }, description: '', isLocked: false },
  { name: '', type: ComponentType.PieChart, props: { colors: ['#0088FE', '#00C49F', '#FFBB28', '#FF8042', '#AF19FF', '#FF4560', '#775DD0'] }, size: { width: 250, height: 250 }, styles: { ...commonStyles, backgroundColor: 'rgba(55, 65, 81, 0.5)' }, description: '', isLocked: false },
  { name: '', type: ComponentType.Group, props: {}, size: { width: 200, height: 200 }, styles: { backgroundColor: 'rgba(82, 113, 149, 0.1)', borderColor: 'rgba(82, 113, 149, 0.5)', borderWidth: 1, borderRadius: 6, borderStyle: 'dashed' }, description: '', isLocked: false },
  { name: '', type: ComponentType.Misc, props: {}, size: { width: 150, height: 50 }, styles: { backgroundColor: 'rgba(250, 204, 21, 0.2)', borderColor: '#facc15', borderWidth: 2, borderRadius: 6, borderStyle: 'dashed', color: '#facc15', fontSize: 14, fontWeight: 500 }, description: '', isLocked: false },
];

export const ICONS_MAP: { [key: string]: React.FC<any> } = {
  MailIcon: MailIcon,
  BellIcon: BellIcon,
  HomeIcon: HomeIcon,
  UserIcon: UserIcon,
  CogIcon: CogIcon,
  SearchIcon: SearchIcon,
  CheckCircleIcon: CheckCircleIcon,
  XCircleIcon: XCircleIcon,
  InformationCircleIcon: InformationCircleIcon,
  ExclamationTriangleIcon: ExclamationTriangleIcon,
  PlayIcon: PlayIcon,
  PauseIcon: PauseIcon,
  ForwardIcon: ForwardIcon,
  BackwardIcon: BackwardIcon,
  XMarkIcon: XMarkIcon,
};

export const COMPONENT_PRESETS: Partial<Record<ComponentType, Preset[]>> = {
  [ComponentType.Button]: [
    { name: 'Standard', props: { text: '버튼', icon: null, kind: 'text' }, styles: {}, type: 'functional' },
    { name: 'Play', props: { text: '', icon: 'PlayIcon', kind: 'icon' }, styles: { borderRadius: 9999 }, type: 'functional' },
    { name: 'Pause', props: { text: '', icon: 'PauseIcon', kind: 'icon' }, styles: { borderRadius: 9999 }, type: 'functional' },
    { name: 'Next', props: { text: '', icon: 'ForwardIcon', kind: 'icon' }, styles: { borderRadius: 9999 }, type: 'functional' },
    { name: 'Previous', props: { text: '', icon: 'BackwardIcon', kind: 'icon' }, styles: { borderRadius: 9999 }, type: 'functional' },
    { name: 'Close', props: { text: '', icon: 'XMarkIcon', kind: 'icon' }, styles: { borderRadius: 9999, backgroundColor: '#6b7280' }, type: 'functional' },
    { name: 'Primary', styles: { backgroundColor: '#2563eb', color: '#ffffff', borderWidth: 0 }, type: 'style' },
    { name: 'Secondary', styles: { backgroundColor: '#4b5563', color: '#ffffff', borderWidth: 0 }, type: 'style' },
    { name: 'Outline', styles: { backgroundColor: 'transparent', color: '#9ca3af', borderWidth: 1, borderColor: '#6b7280' }, type: 'style' },
    { name: 'Ghost', styles: { backgroundColor: 'transparent', color: '#9ca3af', borderWidth: 0 }, type: 'style' },
    { name: 'Link', styles: { backgroundColor: 'transparent', color: '#60a5fa', borderWidth: 0, textDecoration: 'underline' }, type: 'style' },
    { name: 'Success', styles: { backgroundColor: '#16a34a', color: '#ffffff', borderWidth: 0 }, type: 'style' },
    { name: 'Danger', styles: { backgroundColor: '#dc2626', color: '#ffffff', borderWidth: 0 }, type: 'style' },
    { name: 'Pill', styles: { borderRadius: 9999 }, type: 'style' },
  ],
  [ComponentType.Input]: [
    { name: 'Standard', styles: { backgroundColor: '#374151', borderColor: '#6b7280', borderWidth: 1 } },
    { name: 'Quiet', styles: { backgroundColor: 'transparent', borderColor: 'transparent', borderWidth: 0, borderBottomWidth: 1, borderRadius: 0 } },
    { name: 'Pill', styles: { backgroundColor: '#374151', borderColor: '#6b7280', borderWidth: 1, borderRadius: 9999 } },
    { name: 'Modern', styles: { backgroundColor: '#1f2937', borderColor: '#4b5563', borderWidth: 1, borderRadius: 8 } },
  ],
  [ComponentType.Listbox]: [
    { name: 'Standard', styles: { backgroundColor: '#374151', borderColor: '#6b7280', borderWidth: 1 } },
    { name: 'Quiet', styles: { backgroundColor: 'transparent', borderWidth: 0 } },
  ],
  [ComponentType.Container]: [
    { name: 'Card', styles: { backgroundColor: '#1f2937', borderColor: '#4b5563', borderWidth: 1, borderRadius: 12, boxShadow: '0 10px 15px -3px rgba(0,0,0,0.1), 0 4px 6px -2px rgba(0,0,0,0.05)' } },
    { name: 'Glassmorphism', styles: { backgroundColor: 'rgba(31, 41, 55, 0.5)', borderColor: 'rgba(107, 114, 128, 0.3)', borderWidth: 1, borderRadius: 16, backdropFilter: 'blur(10px)' } },
    { name: 'Well', styles: { backgroundColor: '#111827', borderColor: '#374151', borderWidth: 1, borderRadius: 8 } },
    { name: 'Subtle', styles: { backgroundColor: 'rgba(55, 65, 81, 0.3)', borderWidth: 0 } },
  ],
  [ComponentType.Alert]: [
    { name: 'Info (Solid)', props: { type: 'info' }, styles: { backgroundColor: '#3b82f6', color: '#ffffff', borderWidth: 0 } },
    { name: 'Success (Subtle)', props: { type: 'success' }, styles: { backgroundColor: '#1f2937', color: '#86efac', borderColor: '#22c55e', borderLeftWidth: 4, borderWidth: 0 } },
    { name: 'Warning (Top Accent)', props: { type: 'warning' }, styles: { backgroundColor: '#374151', color: '#fcd34d', borderTopWidth: 4, borderColor: '#f59e0b', borderLeftWidth: 0, borderWidth: 0, borderRadius: 4 } },
    { name: 'Error (Outline)', props: { type: 'error' }, styles: { backgroundColor: 'transparent', color: '#fca5a5', borderWidth: 1, borderColor: '#ef4444' } },
  ],
  [ComponentType.Text]: [
    { name: 'Heading', styles: { fontSize: 24, fontWeight: 'bold' } },
    { name: 'Subheading', styles: { fontSize: 18, fontWeight: '600', color: '#d1d5db' } },
    { name: 'Body', styles: { fontSize: 14, fontWeight: '400', color: '#9ca3af' } },
    { name: 'Muted', styles: { fontSize: 12, fontWeight: '400', color: '#6b7280' } },
  ],
  [ComponentType.Image]: [
    { name: 'Rounded', styles: { borderRadius: 16 } },
    { name: 'Circle', styles: { borderRadius: '50%' } },
    { name: 'Shadow', styles: { boxShadow: '0 10px 15px -3px rgba(0,0,0,0.1), 0 4px 6px -2px rgba(0,0,0,0.05)' } },
    { name: 'No Radius', styles: { borderRadius: 0 } },
  ],
  [ComponentType.Tabs]: [
    { name: 'Line', props: { style: 'line' }, styles: {} },
    { name: 'Pill', props: { style: 'pill' }, styles: {} },
    { name: 'Segmented', props: { style: 'segmented' }, styles: {} },
    { name: 'Modern', props: { style: 'pill' }, styles: { backgroundColor: '#1f2937', borderRadius: 8 } },
    { name: 'Minimal', props: { style: 'line' }, styles: { backgroundColor: 'transparent' } },
  ],
  [ComponentType.Accordion]: [
    { name: 'Minimal', styles: { borderWidth: 0, backgroundColor: 'transparent' } },
    { name: 'Separated', styles: { borderWidth: 1, borderColor: '#4b5563', borderRadius: 8 } },
    { name: 'Flush', styles: { borderRadius: 0 } },
  ],
  [ComponentType.Dropdown]: [
      { name: 'Standard', styles: { backgroundColor: '#374151', borderColor: '#6b7280', borderWidth: 1 } },
      { name: 'Quiet', styles: { backgroundColor: 'transparent', borderColor: '#6b7280', borderWidth: 0, borderBottomWidth: 1, borderRadius: 0 } },
  ],
  [ComponentType.Progress]: [
    { name: 'Blue', styles: { barColor: '#2563eb' } },
    { name: 'Green', styles: { barColor: '#16a34a' } },
    { name: 'Slim', styles: { borderRadius: 2, height: 4 } },
    { name: 'Striped', styles: { barColor: '#2563eb', backgroundImage: 'linear-gradient(45deg, rgba(255, 255, 255, 0.15) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, transparent 75%, transparent)' } },
  ],
  [ComponentType.Tooltip]: [
      { name: 'Dark', props: { text: '툴팁 텍스트' } , styles: { backgroundColor: '#111827', color: '#ffffff' } },
      { name: 'Light', props: { text: '툴팁 텍스트' }, styles: { backgroundColor: '#d1d5db', color: '#1f2937' } },
  ],
  [ComponentType.Icon]: [
    { name: 'Light Gray', styles: { color: '#d1d5db' } },
    { name: 'Blue', styles: { color: '#60a5fa' } },
    { name: 'White', styles: { color: '#ffffff' } },
  ],
};